import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatMenuModule,
  MatFormFieldModule,
  MatAutocompleteModule,
  MatButtonModule,
  MatCheckboxModule,
  MatIconModule,
  MatTooltipModule,
  MatSlideToggleModule,
  MatSelectModule,
  MatRadioModule,
  MatInputModule,
  MatSnackBarModule,
  MatSidenavModule,
  MatExpansionModule,
  MatListModule,
  MatDialogModule,
  MatDatepickerModule,
  MatSliderModule,
  MatCardModule,
  MAT_DATE_LOCALE,
  DateAdapter,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatProgressBarModule,
  MatChipsModule,
  MatBottomSheetModule,
  MAT_DATE_FORMATS,
  MatStepperModule,
  MatProgressSpinnerModule,
  MatPaginatorModule,
  MatSortModule,
  
} from '@angular/material';
import { AppDateAdapter, APP_DATE_FORMATS } from "../services/general/datepicker";
@NgModule({
  imports: [
    MatMenuModule,
    MatFormFieldModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCheckboxModule,
    MatIconModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatSelectModule,
    MatRadioModule,
    MatInputModule,
    MatSnackBarModule,
    MatSidenavModule,
    MatExpansionModule,
    MatListModule,
    MatDialogModule,
    MatDatepickerModule,
    MatSliderModule,
    MatCardModule,
    MatTabsModule,
    MatToolbarModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatProgressBarModule,
    MatStepperModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatSortModule,
  ],
  exports: [
    MatMenuModule,
    MatFormFieldModule,
    MatAutocompleteModule,
    MatButtonModule,
    MatCheckboxModule,
    MatIconModule,
    MatTooltipModule,
    MatSlideToggleModule,
    MatSelectModule,
    MatRadioModule,
    MatInputModule,
    MatSnackBarModule,
    MatSidenavModule,
    MatExpansionModule,
    MatListModule,
    MatDialogModule,
    MatDatepickerModule,
    MatSliderModule,
    MatCardModule,
    MatTabsModule,
    MatToolbarModule,
    MatChipsModule,
    MatBottomSheetModule,
    MatProgressBarModule,
    MatStepperModule,
    MatProgressSpinnerModule,
    MatTableModule,
    MatProgressSpinnerModule,
    MatPaginatorModule,
    MatSortModule,
  ],
  providers: [
    {
      provide: DateAdapter, useClass: AppDateAdapter
    },
    {
      provide: MAT_DATE_FORMATS, useValue: APP_DATE_FORMATS
    },
    { provide: MAT_DATE_LOCALE, useValue: 'vi-GB' },
  ]
})
export class MaterialModule { }
